USE master;
GO

ALTER DATABASE AdventureWorks2014 SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 3 DAYS, AUTO_CLEANUP = ON);
GO

SELECT *, 'ALTER TABLE ' + t.TABLE_SCHEMA + '.' + t.TABLE_NAME + ' ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)'
FROM INFORMATION_SCHEMA.TABLES AS t
WHERE t.TABLE_TYPE = 'BASE TABLE'
AND t.TABLE_SCHEMA = 'Person'

USE AdventureWorks2014;
go

ALTER TABLE Person.[Address] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.AddressType ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.StateProvince ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.BusinessEntity ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.BusinessEntityAddress ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.BusinessEntityContact ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.ContactType ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.CountryRegion ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.EmailAddress ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.[Password] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.Person ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.PersonPhone ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)
ALTER TABLE Person.PhoneNumberType ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF)


SELECT * FROM CHANGETABLE(CHANGES Person.Person, 0) AS ct